[package]
name = "GraphLayout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
imageproc = "0.23.0"

[[bin]]
name = "GraphLayout"
path = "main.rs"
